USE [OlAP_Analysis]
GO

/****** Object:  Table [dbo].[DimResult]    Script Date: 12/9/2013 2:47:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DimResult](
	[ResultKey] [int] NOT NULL,
	[ResultName] [nvarchar](100) NULL,
 CONSTRAINT [PK_DimResult] PRIMARY KEY CLUSTERED 
(
	[ResultKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


